# Global System Configuration
# Edit these values when deploying on separate machines.

# --- Master Server ---
master.host=172.16.1.110
master.port=5001

# --- Reducer Server ---
reducer.host=172.16.1.107
reducer.port=8001

# --- Secured Random Generator (SRG) ---
srg.host=172.16.1.107
srg.port=7001
