# Workers Configuration File
# Format: IP:PORT (one entry per line)
# Edit these lines with the actual IP addresses of your 3 machines.
# For local testing, all three can be localhost with different ports.

172.16.1.107:6000
172.16.1.107:6001
172.16.1.110:6002
